version: '3'

services:
  front:
    build:
      context: .
      dockerfile: ./front/Dockerfile
    command: [npm, start]
    ports:
      - 8080:3000
    tty: true
    stdin_open: true
    volumes:
      - type: bind
        source: ./front/rubberducker
        target: /app
