version: '3.8'

services:
  front:
    build:
      context: .
      dockerfile: ./front/Dockerfile
    command: [npm, start]
    ports:
      - '8080:3000'
    tty: true
    stdin_open: true
    volumes:
      - ./front/rubberducker:/app
      - /app/node_modules