version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    command: [npm, start]
    ports:
      # 同じportを使用しないとローカルではエラーが発生した
      # react-scripts内のwebpack-dev-serverでエラー
      - 3000:3000
    tty: true
    stdin_open: true
    volumes:
      - type: bind
        source: ./frontend/rubberducker
        target: /app
